package net.rim99.demo.account;

import net.rim99.demo.account.repository.Mybatis;
import net.rim99.demo.account.resource.Resource;
import net.rim99.demo.account.startup.Config;
import net.rim99.demo.account.support.ServerManager;
import net.rim99.demo.account.support.guice.GlobalInjector;
import net.rim99.demo.account.support.config.ConfigManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        ConfigManager.initialize(Config.register());
        GlobalInjector.builder().addModule(Mybatis.getModule());
        ServerManager startup = new ServerManager();
        startup.start(ConfigManager.get(), Resource.config());
    }
}
