import net.rim99.demo.account.startup.ServerManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        ServerManager startup = new ServerManager();
        startup.start();
    }
}
