import net.rim99.demo.account.repository.Mybatis;
import net.rim99.demo.account.startup.Config;
import net.rim99.demo.account.support.ServerManager;
import net.rim99.demo.account.support.Repositories;
import net.rim99.demo.account.support.config.ConfigManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Repositories.initializeFactory(Mybatis.getModule());
        ConfigManager.initialize(Config.register());
        ServerManager startup = new ServerManager();
        startup.start(ConfigManager.get());
    }
}
